import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from 'styles/Home.module.css'

const Slug = ({ posts }: { posts: Array<{ id: string, title: string, slug: string }> }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {posts.map((post, index) => (
            <li key={index}><Link href={"/product/" + post.slug}>{post.title}</Link></li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export default Slug

export async function getStaticPaths() {

  const res = await fetch('https://api.spacedev.vn/api/frontend/v1.0/vn4-ecommerce/product/get-featured');
  const posts = await res.json();

  const paths = posts.products.map((post: { id: string, title: string, slug: string }) => ({
    params: post,
  }))

  return {
    paths: paths,
    fallback: false, // can also be true or 'blocking'
  }
}

export async function getStaticProps() {

  const res = await fetch('https://api.spacedev.vn/api/frontend/v1.0/vn4-ecommerce/product/get-featured');
  const posts = await res.json();

  return {
    props: {
      posts: posts.products,
    },
  }
}
