import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from 'styles/Home.module.css'

const Slug = ({ post }: { post: { id: string, title: string, slug: string, content: string } }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">Back</Link>
        {post.content}
      </main>
    </div>
  )
}

export default Slug

// export async function getStaticPaths() {

//   const res = await fetch('https://api.spacedev.vn/api/frontend/v1.0/vn4-e-learning/page/get-page-of-group', {
//     method: 'POST',
//     headers: {
//       'Content-Type': 'application/json'
//     },
//     body: JSON.stringify({
//       group: 'legal'
//     })
//   });

//   const posts = await res.json();

//   const paths = posts.pages.map((post: { id: string, title: string, slug: string }) => ({
//     params: post,
//   }))

//   return {
//     paths: paths,
//     fallback: false, // can also be true or 'blocking'
//   }
// }

export async function getServerSideProps({ params }: { params: { slug: string } }) {

  const res = await fetch('https://api.spacedev.vn/api/frontend/v1.0/vn4-e-learning/page/get-content', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      group: "legal",
      post: params.slug
    })
  });

  const posts = await res.json();

  return {
    props: {
      post: posts.post,
    },
  }
}
